routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('layouts.app');
// });

Route::get('/faqs', function () {
    return view('home.includes.faqs');
});

Route::get('/contactus', function () {
    return view('home.includes.contactus');
});
Route::get('/aboutus', function () {
    return view('home.includes.aboutus');
});

	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
	Route::prefix('admin')->group(function() {
		Route::get('/', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
		Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
		Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
		Route::get('/dashboard', 'AdminController@index')->name('admin.dashboard');
		Route::post('/logout', 'Auth\AdminLoginController@logout')->name('logout');
		Route::get('/change-password', 'AdminController@showChangePass')->name('changepassword');
		Route::post('/change-password', 'AdminController@postChangePass')->name('changepassword');

		Route::resource('category', 'Admin\CategoryController');
		Route::resource('banner', 'Admin\BannerController');
		Route::resource('product', 'Admin\ProductController');
		Route::resource('manufacturer', 'Admin\ManufacturerController');
		Route::resource('setting', 'Admin\SettingController');


		// Password reset routes
	    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
	    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
	});

	Route::get('/', 'Home\HomeController@index')->name(' ');
	Route::get('/products', 'Home\HomeController@getProductList')->name('product.list');
	// Route::get('/quickview/{id}', 'Home\HomeController@quickView')->name('quickview');
	Route::get('/singleproduct/{slug}', 'Home\HomeController@singleProduct')->name('single.product');
	Route::get('/product/{category}/{subcategory}', 'Home\HomeController@categoryProduct')->name('category.product');
	Route::post('enquiry/submit', 'Home\HomeController@addEnquiry')->name('enquiry.submit');

app/Http/Controllers/Admin/ManufacturerController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\ManufacturerRequest;
use App\Admin\Manufacturer;

class ManufacturerController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Index View of Manufacturer
     *
     * @return mixed
     */
    public function index()
    {
        $manufacturers=Manufacturer::all();
        return view('admin.manufacturer.admin_table_manufacturer')->with(compact('manufacturers'));
    }

    /**
     * Create Manufacturer
     *
     * @return mixed
     */
    public function create()
    {
        return view('admin.manufacturer.admin_add_manufacturer');
    }

    /**
     * Update Manufacturer
     *
     * @param ManufacturerRequest $request
     * @return mixed
     */
    public function store(Request $request)
    {
        $data = $request->all();
        Manufacturer::create($data);
        $request->session()->flash('success', 'Manufacturer Added Successfully!');
        return redirect()->route('manufacturer.index');
    }

    /**
     * Edit Form Data
     *
     * @param $id
     * @return mixed
     */
    public function edit($id)
    {
        // $categories= Category::all();
        $manufacturer=Manufacturer::find($id);
        return view('admin.manufacturer.admin_edit_manufacturer')->with(compact('manufacturer'));
    }


    /**
     * Update Manufacturer Data
     *
     * @param ManufacturerRequest $request
     * @param $id
     * @return mixed
     */
    public function update(Request $request, $id)
    {
        // dd($data);
        $data = $request->all();
        Manufacturer::findOrFail($id)->update($data);
        $request->session()->flash('success', 'Manufacturer Changes Applied Successfully!');
        return redirect()->route('manufacturer.index');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
            Manufacturer::findOrFail($id)->delete();
            return 'deleted';
    }

}

resources/views/admin/manufacturer/admin_add_manufacturer.blade.php
@extends('admin.layouts.master')
    @section('pageCss')
    <link href="{{ asset('assets/admin/js/colorbox/example2/colorbox.css') }}" rel="stylesheet" type="text/css"/>
    <!-- Select2 -->
    <link href="{{asset('assets/admin/vendors/select2/dist/css/select2.min.css')}}" rel="stylesheet">
    @endsection('pageCss')
@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Manufacturer
                        <small>Add Manufacturer</small>
                    </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    @if (count($errors) > 0)
                    <div class="alert alert-danger alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                        </button>
                        <strong>OOPS! You might have missed to fill some required fields. Please check the errors.  <strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>

                    </div>
                    @endif

                    <form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" required="required" method="post" action="{{route('manufacturer.store')}}">
                        {{csrf_field()}}

                        


                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Manufacturer Name <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="name" name="name" class="form-control col-md-7 col-xs-12" placeholder="Manufacturer Name" value="{{old('name')}}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Image</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="feature_image" name="image" class="form-control col-md-7 col-xs-12" placeholder="Manufacturer Image">
                                <a href="" class="popup_selector" data-inputid="feature_image">Browse Image</a>
                            </div>
                        </div>

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="reset" class="btn btn-primary" onclick="history.go(-1);">Cancel</button>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('pageScript')
    <script src="{{ asset('assets/admin/js/colorbox/jquery.colorbox-min.js') }}"></script>
    <script type="text/javascript" src="{{asset('packages/barryvdh/elfinder/js/standalonepopup.min.js')}}"></script>
    <!-- Select2 -->
    <script type="text/javascript"
                    src="{{asset('assets/admin/vendors/select2/dist/js/select2.full.min.js')}}"></script>

    <script type="text/javascript">
         $(".select2_multiple").select2({
                        maximumSelectionLength: 10,
                        allowClear: true
                    });
    </script>
@endsection

resources/views/admin/manufacturer/admin_edit_manufacturer.blade.php
@extends('admin.layouts.master')
    @section('pageCss')
        <link href="{{ asset('assets/admin/js/colorbox/example2/colorbox.css') }}" rel="stylesheet" type="text/css"/>
        <!-- Select2 -->
        <link href="{{asset('assets/admin/vendors/select2/dist/css/select2.min.css')}}" rel="stylesheet">
    @endsection
@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Manufacturer
                        <small>Edit Manufacturer</small>
                    </h2>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    @if (count($errors) > 0)
                        <div class="alert alert-danger alert-dismissible fade in" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                            </button>
                            <strong>OOPS! You might have missed to fill some required fields. Please check the errors.  <strong>

                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>

                        </div>
                    @endif

                    <form id="myForm" data-parsley-validate="" class="form-horizontal form-label-left"
                      required="required" method="post" action="{{route('manufacturer.update',$manufacturer->id)}}">
                      <input type="hidden" name="_method" value="PUT">
                      {{csrf_field()}}

                        

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Manufacturer Name <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="name" name="name" class="form-control col-md-7 col-xs-12" placeholder="Manufacturer Name" value="{{$manufacturer->name}}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Image</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="feature_image" name="image" class="form-control col-md-7 col-xs-12" placeholder="Manufacturer Image" value="{{$manufacturer->image}}">
                                <a href="" class="popup_selector" data-inputid="feature_image">Browse Image</a>
                            </div>
                        </div>

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="reset" class="btn btn-primary" onclick="window.location.replace('{{route('manufacturer.index')}}')">Cancel</button>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection('content')
@section('pageScript')
    <script src="{{ asset('assets/admin/js/colorbox/jquery.colorbox-min.js') }}"></script>
    <script type="text/javascript" src="{{asset('packages/barryvdh/elfinder/js/standalonepopup.min.js')}}"></script>

     <!-- Select2 -->
    <script type="text/javascript"
                    src="{{asset('assets/admin/vendors/select2/dist/js/select2.full.min.js')}}"></script>

    <script type="text/javascript">
         $(".select2_multiple").select2({
                        maximumSelectionLength: 10,
                        allowClear: true
                    });
    </script>
@endsection

resources/views/admin/manufacturer/admin_importexport_manufacturer.blade.php
@extends('admin.layouts.master')
@section('pageCss')
<!-- Datatables -->
<link href="{{asset('assets/admin/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet')}}">
<link href="{{asset('assets/admin/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')}}" rel="stylesheet">
<!-- PNotify -->
<link href="{{asset('assets/admin/vendors/pnotify/dist/pnotify.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/pnotify/dist/pnotify.buttons.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin//vendors/pnotify/dist/pnotify.nonblock.css')}}" rel="stylesheet">
<!-- Datatables -->
<!-- Select2 -->
    <link href="{{asset('assets/admin/vendors/select2/dist/css/select2.min.css')}}" rel="stylesheet">
@endsection
@section('content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
       @if (Session::has('notifier.notice'))
       <script>
        new PNotify({!! Session::get('notifier.notice') !!});
    </script>
    @endif
    @if(Session::has('message'))
    <div class="alert {{ Session::get('alert-class', 'alert-info') }} fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <p>{{ Session::get('message') }}</p>
        @endif
    </div>
    <div class="x_panel">
        <div class="x_title">
            <h2>Manufacturer <small> Import/Export  </small></h2>
            <div class="pull-right">
                <a href="{{route('admin.manufacturer.index')}}" class="btn btn-info btn-md">
                     Back
                </a>
                    <a href="{{route('admin.manufacturer.import',['xls',$storeId])}}"><button class="btn btn-success">Download Excel xls</button></a>
                            <a href="{{route('admin.manufacturer.import',['xlsx',$storeId])}}"><button class="btn btn-success">Download Excel xlsx</button></a>
                            <a href="{{route('admin.manufacturer.import',['csv',$storeId])}}"><button class="btn btn-success">Download CSV</button></a>
            </div>
            <div class="clearfix"></div>
            </div>
          <div class="x_content">
            @if (count($errors) > 0)
                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                    </button>
                    <strong>OOPS! You might have missed to fill some required fields. Please check the errors.  <strong>

                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>

                </div>
            @endif
            @if(Session::has('success'))
                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">
                    {{ Session::get('success') }}
                </p>
            @endif 
            <small>  Store Name :: {{$storename}}</small>
            <form  action="{{route('admin.manufacturer.export')}}" class="form-horizontal" method="post" enctype="multipart/form-data">

                {{ csrf_field() }}
                
                <input type="hidden" name="storeId" value="{{$storeId}}" />

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="coupon-discount">Import File<span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                          <input type="file" name="import_file" />
                    </div>
                </div>

                <hr/>
                <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="coupon-discount"><span class="required"></span>
                            </label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                          <button class="btn btn-primary">Import CSV or Excel File</button>
                    </div>
                </div>

            </form>

        </div>

</div>
</div>


</div>
@endsection('content')
@section('pageScript')

<!-- Datatables -->
<script src="{{asset('assets/admin/vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-scroller/js/datatables.scroller.min.js')}}"></script>
<!-- Datatables -->
<!-- iCheck -->
<script src="{{asset('assets/admin/vendors/iCheck/icheck.min.js')}}"></script>
<!-- PNotify -->
<script src="{{asset('assets/admin/vendors/pnotify/dist/pnotify.js')}}"></script>
<script src="{{asset('assets/admin/vendors/pnotify/dist/pnotify.buttons.js')}}"></script>
<script src="{{asset('assets/admin/vendors/pnotify/dist/pnotify.nonblock.js')}}"></script>
@include('laravelPnotify::notify')
<!-- Datatables -->
<script>
    $(document).ready(function() {


        $('#datatable').dataTable();

        $('#datatable-keytable').DataTable({
            keys: true
        });

        $('#datatable-responsive').DataTable();

        $('#datatable-fixed-header').DataTable({
            fixedHeader: true
        });

        var $datatable = $('.datatable');

        $datatable.dataTable({
            'order': [[ 1, 'asc' ]],
            'columnDefs': [
            { orderable: false, targets: [0] }
            ]
        });
        $datatable.on('draw.dt', function() {
            $('input').iCheck({
                checkboxClass: 'icheckbox_flat-green'
            });
        });

    });
</script>
<!-- /Datatables -->
    <script type="text/javascript"
                    src="{{asset('assets/admin/vendors/select2/dist/js/select2.full.min.js')}}"></script>

    <script type="text/javascript">
         $(".select2_multiple").select2({
                        maximumSelectionLength: 10,
                        allowClear: true
                    });
    </script>
@endsection('pageScript')

resources/views/admin/manufacturer/admin_table_manufacturer.blade.php
@extends('admin.layouts.master')
@section('pageCss')
         <!-- Datatables -->
<link href="{{asset('assets/admin/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet')}}">
<link href="{{asset('assets/admin/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')}}" rel="stylesheet">

<link rel="stylesheet" href="{{ asset('assets/home/css/iziToast.min.css')}}">
    
<script type="text/javascript" src="{{ asset('assets/home/js/iziToast.min.js')}}"></script>
<!-- Datatables -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
                    @if(Session::has('success'))
                        <script type="text/javascript">
                        iziToast.success({
                            title: 'Success',
                            message: '{{ Session::get('success') }}',
                            position: 'topRight'
                                    });
                        </script>
                    @endif
                    <div class="x_title">
                    <h2>Manufacturer <small> List</small></h2>
                    <div class="pull-right">
                        <a href="{{route('manufacturer.create')}}" class="btn btn-info btn-md">
                            <span class="glyphicon glyphicon-plus"></span> Add
                        </a>
                        <a href="#" class="btn btn-danger btn-md deleteData">
                            <span class="glyphicon glyphicon-trash" ></span> Delete
                        </a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <table id="datatable-checkbox" class="table table-striped table-bordered bulk_action">
                        <thead>
                        <tr>
                            <th><input type="checkbox" id="check-all" class="flat"></th>
                            <th>Manufacturer Name</th>
                            <th>Action</th>

                        </tr>
                        </thead>


                        <tbody>
                        @foreach($manufacturers as $m)
                            <tr>
                                <td><input type="checkbox" class="flat" value="{{$m->id}}" name="table_records"></td>
                                <td>{{$m->name}}</td>
                                <td><a href="{{route('manufacturer.edit',$m->id)}}" class="btn btn-default btn-sm">

                                        <i class="fa fa-edit"></i> Edit
                                    </a></td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
    </div>
@endsection
@section('pageScript')

<!-- Datatables -->
<script src="{{asset('assets/admin/vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
<script src="{{asset('assets/admin/vendors/datatables.net-scroller/js/dataTables.scroller.min.js')}}"></script>
<!-- Datatables -->
<!-- iCheck -->
<script src="{{asset('assets/admin/vendors/iCheck/icheck.min.js')}}"></script>

<!-- Datatables -->
    <script>
        $(document).ready(function() {


            $('#datatable').dataTable();

            $('#datatable-keytable').DataTable({
                keys: true
            });

            $('#datatable-responsive').DataTable();

            $('#datatable-fixed-header').DataTable({
                fixedHeader: true
            });

            var $datatable = $('#datatable-checkbox');

            $datatable.dataTable({
                'order': [[ 1, 'asc' ]],
                'columnDefs': [
                    { orderable: false, targets: [0] }
                ]
            });
            $datatable.on('draw.dt', function() {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_flat-green'
                });
            });

        });
    </script>
    <!-- /Datatables -->

    <script type="text/javascript">
        var deleteRow = $('.deleteData');
        var route = "manufacturer";
        var token = "{{csrf_token()}}";
        deleteTableRow(deleteRow,route,token);
    </script>
@endsection