routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('layouts.app');
// });

Route::get('/faqs', function () {
    return view('home.includes.faqs');
});

Route::get('/contactus', function () {
    return view('home.includes.contactus');
});
Route::get('/aboutus', function () {
    return view('home.includes.aboutus');
});

	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
	Route::prefix('admin')->group(function() {
		Route::get('/', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
		Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
		Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
		Route::get('/dashboard', 'AdminController@index')->name('admin.dashboard');
		Route::post('/logout', 'Auth\AdminLoginController@logout')->name('logout');
		Route::get('/change-password', 'AdminController@showChangePass')->name('changepassword');
		Route::post('/change-password', 'AdminController@postChangePass')->name('changepassword');

		Route::resource('category', 'Admin\CategoryController');
		Route::resource('banner', 'Admin\BannerController');
		Route::resource('product', 'Admin\ProductController');
		Route::resource('manufacturer', 'Admin\ManufacturerController');
		Route::resource('setting', 'Admin\SettingController');


		// Password reset routes
	    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
	    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
	});

	Route::get('/', 'Home\HomeController@index')->name(' ');
	Route::get('/products', 'Home\HomeController@getProductList')->name('product.list');
	// Route::get('/quickview/{id}', 'Home\HomeController@quickView')->name('quickview');
	Route::get('/singleproduct/{slug}', 'Home\HomeController@singleProduct')->name('single.product');
	Route::get('/product/{category}/{subcategory}', 'Home\HomeController@categoryProduct')->name('category.product');
	Route::post('enquiry/submit', 'Home\HomeController@addEnquiry')->name('enquiry.submit');

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Admin\Setting;
use App\Http\Requests\Admin\SettingRequest;
use App\Http\Controllers\Controller;
use DB;

class SettingController extends Controller
{
    /**
     * SettingEloquentRepository constructor.
     * @param Setting $setting
     */
    public function __construct(Setting $setting)
    {
        $this->model = $setting;
        $this->middleware('auth:admin');

    }

    /**
     * Index View of Setting
     *
     * @return mixed
     */
    public function index()
    {

        return view('admin.setting.admin_table_setting', ['settings' => $this->getSettingByCodeAndKey('config','config_name')]);
    }

    /**
     * Edit Form Data
     *
     * @param $code
     * @return mixed
     */
    public function edit($code)
    {
        $setting = $this->getSettingByCode($code);
        // $orderStatus = Setting::all();
        return view('admin.setting.admin_edit_setting')->with(compact('setting','orderStatus','information'));
    }


    /**
     * Update Setting Data
     *
     * @param SettingRequest $request
     * @param $code
     * @return mixed
     */
    public function update(SettingRequest $request, $code)
    {
        $data = $request->except('_method','_token');
        $this->updateSettingByCode($code, $data);
        $request->session()->flash('success', 'Setting Changes Applied Successfully!');
        return redirect()->route('setting.index');
    }

    public function updateSettingByCode($code,$data)
    {
        $this->model->where('code','=',$code)->delete();
        foreach($data as $key=>$value) {
            if (substr($key, 0, strlen($code)) == $code) {
                if (!is_array($value)) {
                    DB::table('settings')->insert(['code' => $code, 'key' => $key, 'value' => $value]);
                } else {
                    DB::table('settings')->insert(['code' => $code, 'key' => $key, 'value' => json_encode($value),'serialized' =>1]);
                }
            }
        }
        return true;
    }


    /**
     * Get Setting By Code
     *
     * @param $code
     * @return array
     */
    public function getSettingByCode($code)
    {
        $settingData = [];
        $data = $this->model->where('code','=',$code)->get();
        foreach($data as $d){
            if(!$d['serialized']){
                $settingData[$d['key']] = $d->value;
            }
            else{
                $settingData[$d['key']] = json_decode($d->value,true);
            }
        }
        return $settingData;

    }

    /**
     * Get Settings By Code And Key
     *
     * @param $code
     * @param $key
     * @return mixed
     */
    public function getSettingByCodeAndKey($code,$key)
    {
       return $this->model->where('code','=',$code)->where('key','=',$key)->get();

    }
}

resources/views/admin/setting/admin_edit_setting.blade.php
    @extends('admin.layouts.master')
    @section('pageCss')
    <link href="{{ asset('assets/admin/js/colorbox/example2/colorbox.css') }}" rel="stylesheet" type="text/css" />
    @endsection('pageCss')
    @section('content')
    <div class="clearfix"></div>
    <div class="row">
     @foreach ($errors->all() as $error)
     <p class="error">{{ $error }}</p>
     @endforeach

     <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Setting <small>Edit Site Settings</small></h2>
          <div class="clearfix"></div>
        </div>
        <div >
          <form id="myForm" data-parsley-validate="" class="form-horizontal form-label-left"
          required="required" method="post" action="{{route('setting.update','config')}}">
          <input type="hidden" name="_method" value="PUT">
          {{csrf_field()}}
          <div id="wizard" class="form_wizard wizard_horizontal">
            <ul class="wizard_steps">
              <li>
                <a href="#step-1">
                  <span class="step_no">1</span>
                  <span class="step_descr">
                    Step 1<br/>
                    <small>General</small>
                  </span>
                </a>
              </li>
              <li>
                <a href="#step-2">
                  <span class="step_no">2</span>
                  <span class="step_descr">
                    Step 2<br/>
                    <small>Data</small>
                  </span>
                </a>
              </li>
            </ul>
            <div id="step-1">
            
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="store-name">Site
                    Name<span class="required">*</span>
                  </label>
                  <div class="col-md-7 col-sm-6 col-xs-12">
                    <input type="text" name="config_name" id="config_name"
                    value="{{$setting['config_name']}}"
                    class="form-control col-md-7 col-xs-12" placeholder="Site Name">
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">
                    Logo
                  </label>
                  <div class="col-md-7 col-sm-6 col-xs-12">
                    <input type="text" id="feature_image" name="config_logo"
                    class="form-control col-md-7 col-xs-12"
                    value="{{$setting['config_logo']}}" placeholder="Site Logo">
                    <a href="" class="popup_selector" data-inputid="feature_image">Browse
                      Image</a>
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="address">Address
                    <span class="required"></span>
                  </label>
                  <div class="col-md-7 col-sm-6 col-xs-12">
                    <textarea rows="4" cols="50" name="config_address" id='meta-tag-description'
                    class="form-control col-md-7 col-xs-12"
                    placeholder="Address">{{$setting['config_address']}}</textarea>
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Email">Email<span
                    class="required">*</span>
                  </label>
                  <div class="col-md-7 col-sm-6 col-xs-12">
                    <input type="text" name="config_email" id="config_email"
                    value="{{$setting['config_email']}}"
                    class="form-control col-md-7 col-xs-12" placeholder="Email">
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telephone">Telephone<span
                    class="required">*</span>
                  </label>
                  <div class="col-md-7 col-sm-6 col-xs-12">
                    <input type="text" name="config_telephone" id="config_telephone"
                    value="{{$setting['config_telephone']}}"
                    class="form-control col-md-7 col-xs-12" placeholder="Telephone">
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="Fax">Fax
                  </label>
                  <div class="col-md-7 col-sm-6 col-xs-12">
                    <input type="text" name="config_fax" id="config_fax"
                    value="{{$setting['config_fax']}}" class="form-control col-md-7 col-xs-12"
                    placeholder="Fax">
                  </div>
                </div>

            </div>
            <div id="step-1">
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="meta-tag-title">Meta
                    Title <span class="required">*</span>
                  </label>
                  <div class="col-md-7 col-sm-6 col-xs-12">
                    <input type="text" name="config_meta_title" id="first-name"
                    value="{{$setting['config_meta_title']}}"
                    class="form-control col-md-7 col-xs-12" placeholder="Meta Title">
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="meta-tag-description">Meta
                    Tag Description <span class="required"></span>
                  </label>
                  <div class="col-md-7 col-sm-6 col-xs-12">
                    <textarea rows="4" cols="50" name="config_meta_description"
                    id='meta-tag-description' class="form-control col-md-7 col-xs-12"
                    placeholder="Meta Tag Description">{{$setting['config_meta_description']}}</textarea>
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="meta-keywords">Meta
                    Tag Keyword <span class="required"></span>
                  </label>
                  <div class="col-md-7 col-sm-6 col-xs-12">
                    <input type="text" name="config_meta_keyword" id="first-name"
                    value="{{$setting['config_meta_keyword']}}"
                    class="form-control col-md-7 col-xs-12" placeholder="Meta Tag Keyword">
                  </div>
                </div>

            </div>

                
              
    </form>
    </div>


    </div>
    <!-- End SmartWizard Content -->


    </div>
    </div>
    </div>
    </div>
    @endsection

    @section('pageScript')
    <script type="text/javascript" src="{{ asset('assets/admin/js/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/admin/js/colorbox/jquery.colorbox-min.js') }}"></script>
    <script type="text/javascript" src="{{asset('packages/barryvdh/elfinder/js/standalonepopup.min.js')}}"></script>

    <script src="{{asset('assets/admin/vendors/iCheck/icheck.min.js')}}"></script>
    {{-- <script src="{{ asset('assets/admin/js/colorbox/jquery.colorbox-min.js') }}"></script> --}}

    <script src="{{asset('assets/admin/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/jquery.hotkeys/jquery.hotkeys.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/google-code-prettify/src/prettify.js')}}"></script>

    <script type="text/javascript">
     CKEDITOR.replace( 'messageArea',
     {
      customConfig : 'config.js',
      toolbar : 'simple'
    })
    </script> 
    <script>
      $(document).ready(function() {
        // alert('hello');

        $('#wizard').smartWizard();

        $('#wizard_verticle').smartWizard({
          transitionEffect: 'slide'
        });

        $('.buttonNext').addClass('btn btn-success');
        $('.buttonPrevious').addClass('btn btn-primary');
        $('.buttonFinish').addClass('btn btn-default');
        $(".buttonFinish").click(function(){
          $('#myForm').submit();
        });
      });
    </script>




  @endsection

resources/views/admin/setting/admin_table_setting.blade.php
@extends('admin.layouts.master')
@section('pageCss')
         <!-- Datatables -->
<link href="{{asset('assets/admin/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet')}}">
<link href="{{asset('assets/admin/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')}}" rel="stylesheet">
<!-- PNotify -->
<link href="{{asset('assets/admin/vendors/pnotify/dist/pnotify.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin/vendors/pnotify/dist/pnotify.buttons.css')}}" rel="stylesheet">
<link href="{{asset('assets/admin//vendors/pnotify/dist/pnotify.nonblock.css')}}" rel="stylesheet">
<!-- Datatables -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            @if(Session::has('success'))
                <script type="text/javascript">
                iziToast.success({
                    title: 'Success',
                    message: '{{ Session::get('success') }}',
                    position: 'topRight'
                });
                </script>
                 @elseif(Session::has('warning'))
                 <script type="text/javascript">
                 iziToast.warning({
                     title: 'Warning',
                     message: '{{ Session::get('warning') }}',
                     position: 'topRight'
                 });
                 </script>

            @endif
                    </div>
            <div class="x_panel">
                <div class="x_title">
                    <h2>Site Settings </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <table id="datatable-checkbox" class="table table-striped table-bordered bulk_action">
                        <thead>
                        <tr>
                            <th><input type="checkbox" id="check-all" class="flat"></th>
                            <th>Site Name</th>
                            <th>Action</th>

                        </tr>
                        </thead>


                        <tbody>
                        @foreach($settings as $s)
                        <tr> 
                            <td><input type="checkbox" class="flat" value="{{$s->code}}" name="table_records"></td>
                            <td>{{$s->value}}</td>
                            <td><a href="{{route('setting.edit',$s->code)}}" class="btn btn-default btn-sm">

                                    <i class="fa fa-edit"></i> Edit
                                </a></td>
                        </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>


    </div>
@endsection
@section('pageScript')

        <!-- Datatables -->
    <script src="{{asset('assets/admin/vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/datatables.net-scroller/js/datatables.scroller.min.js')}}"></script>
    <!-- Datatables -->
    <!-- iCheck -->
    <script src="{{asset('assets/admin/vendors/iCheck/icheck.min.js')}}"></script>
    <!-- PNotify -->
    <script src="{{asset('assets/admin/vendors/pnotify/dist/pnotify.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/pnotify/dist/pnotify.buttons.js')}}"></script>
    <script src="{{asset('assets/admin/vendors/pnotify/dist/pnotify.nonblock.js')}}"></script>
    @include('laravelPnotify::notify')
  <!-- Datatables -->
    <script>
        $(document).ready(function() {


            $('#datatable').dataTable();

            $('#datatable-keytable').DataTable({
                keys: true
            });

            $('#datatable-responsive').DataTable();

            $('#datatable-fixed-header').DataTable({
                fixedHeader: true
            });

            var $datatable = $('#datatable-checkbox');

            $datatable.dataTable({
                'order': [[ 1, 'asc' ]],
                'columnDefs': [
                    { orderable: false, targets: [0] }
                ]
            });
            $datatable.on('draw.dt', function() {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_flat-green'
                });
            });

        });
    </script>
    <!-- /Datatables -->

    <script type="text/javascript">
        $('.deleteData').click(function(){
            if(!$("input:checkbox").is(":checked")){
                new PNotify({
                    title: 'Warning',
                    text: 'No Data Selected. Please select data to delete.',
                    hide: false,
                    styling: 'bootstrap3'
                });
            }else{
                if(confirm("Are you sure you want to delete ??")){
                    var category_id = [];
                    $.each($("input[name='table_records']:checked"), function(){
                        category_id.push($(this).val());
                    });
                    console.log(category_id);


                    /** Delete data ***/
                    $.ajax({
                        type: "DELETE",
                        url: "category/" + category_id,
                        data:{
                            "_token":"{{csrf_token()}}"
                        },
                        success: function(msg){
                            new PNotify({
                                title: 'Success',
                                text: 'Data Deleted Successfully. Loading ....',
                                hide: false,
                                type:'success',
                                styling: 'bootstrap3'
                            });
                            setTimeout(function(){// wait for 5 secs(2)
                                location.reload(); // then reload the page.(3)
                            }, 2000);

                        }

                    });

                    /** Delete Data **/



                }
            }
        });
    </script>
@endsection