routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('layouts.app');
// });

Route::get('/faqs', function () {
    return view('home.includes.faqs');
});

Route::get('/contactus', function () {
    return view('home.includes.contactus');
});
Route::get('/aboutus', function () {
    return view('home.includes.aboutus');
});

	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('login');
	Route::prefix('admin')->group(function() {
		Route::get('/', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
		Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
		Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
		Route::get('/dashboard', 'AdminController@index')->name('admin.dashboard');
		Route::post('/logout', 'Auth\AdminLoginController@logout')->name('logout');
		Route::get('/change-password', 'AdminController@showChangePass')->name('changepassword');
		Route::post('/change-password', 'AdminController@postChangePass')->name('changepassword');

		Route::resource('category', 'Admin\CategoryController');
		Route::resource('banner', 'Admin\BannerController');
		Route::resource('product', 'Admin\ProductController');
		Route::resource('manufacturer', 'Admin\ManufacturerController');
		Route::resource('setting', 'Admin\SettingController');


		// Password reset routes
	    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
	    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');
	});

	Route::get('/', 'Home\HomeController@index')->name(' ');
	Route::get('/products', 'Home\HomeController@getProductList')->name('product.list');
	// Route::get('/quickview/{id}', 'Home\HomeController@quickView')->name('quickview');
	Route::get('/singleproduct/{slug}', 'Home\HomeController@singleProduct')->name('single.product');
	Route::get('/product/{category}/{subcategory}', 'Home\HomeController@categoryProduct')->name('category.product');
	Route::post('enquiry/submit', 'Home\HomeController@addEnquiry')->name('enquiry.submit');

resources/views/admin/includes/asidebar.blade.php
<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar naadmin.dashboard.indexv_title" style="border: 0;">
                    {{-- @if($setting['config_logo']!='') --}}
                        {{-- <a href="{{route('dashboard.index')}}" class="site_title"><img  src="{{ asset($setting['config_logo']) }}" alt="" style=""></a>
                    @else --}}
                        <a href="{{route('admin.dashboard')}}" class="site_title"><img  src="{{asset('')}}assets/home/images/suvalaav-logo.svg" alt="" style=""></a>
                    {{-- @endif --}}


                </div>
                <div class="clearfix"></div>
                <!-- menu profile quick info -->
                <div class="profile">
                        <div class="profile_pic">
                            <img  src="{{asset('')}}assets/admin/images/defaultimage.png" alt="" class="img-circle profile_img">
                        </div>

                    <div class="profile_info">
                        <span>Welcome,</span>
                        @if(Auth::user() != null)
                        <h2>{{Auth::user()->name}}</h2>
                        @else
                        <h2>Admin</h2>
                        @endif
                    </div>
                </div>
                <!-- /menu profile quick info -->
                <br/>
                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <ul class="nav side-menu">
                        </ul>

                        <ul class="nav side-menu">
                            <li><a href="{{route('admin.dashboard')}}"><i class="fa fa-dashboard fw"></i> Dashboard </a>
                            </li>
                        </ul>
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-tags fw"></i> Catalog <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{{route('category.index')}}">Categories</a></li>
                                    <li><a href="{{route('product.index')}}">Products</a></li>
                                    <li><a href="{{route('manufacturer.index')}}">Manufacturers</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-television fw"></i> Design <span
                                            class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{{route('banner.index')}}">Banners</a></li>
                                </ul>
                            </li>
                        </ul>
                        {{-- <ul class="nav side-menu">
                            <li><a><i class="fa fa-user fw"></i> Customers <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{{route('customer.index')}}">Customers</a></li>
                                    <li><a href="{{route('customergroup.index')}}">Customer Groups</a></li>
                                    <li><a href="{{route('customerfamilysize.index')}}">Customer Family Size</a></li>
                                    <li><a href="{{route('duration.index')}}">Customer FamilyWishlist Duration</a></li>
                                    <li><a href="{{route('customerproductsuggestion.index')}}">Customer Product Suggestion</a></li>
                                </ul>
                            </li>
                        </ul> --}}
                        {{-- <ul class="nav side-menu">
                            <li><a><i class="fa fa-share-alt fw"></i> Marketing <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{{route('marketing.index')}}">Marketing</a></li>
                                    <li><a href="{{route('mail.index')}}">Mail</a></li>
                                    <li><a href="{{route('offer.index')}}">Offer</a></li>
                                    <li><a href="{{route('coupon.index')}}">Coupons</a></li>
                                    <li><a>Discounts<span class="fa fa-chevron-down"></span> </a>
                                        <ul class="nav child_menu">
                                            <li><a href="{{route('discounttype.index')}}">Discount Type </a>
                                            <li><a href="{{route('discount.index')}}">Discounts</a></li>
                                        </ul>
                                    </li>

                                    <li><a>Combo Offers<span class="fa fa-chevron-down"></span> </a>
                                        <ul class="nav child_menu">
                                            <li><a href="{{route('combotype.index')}}">Combo Offer Type </a>
                                            <li><a href="{{route('combooffer.index')}}">Combo Offers</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul> --}}
                       {{-- @if(Sentinel::hasAccess('admin')) --}}
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-cog fw"></i> System <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{{route('setting.index')}}">Site Settings </a></li>
                                    {{-- <li><a>Localization <span class="fa fa-chevron-down"></span> </a>
                                        <ul class="nav child_menu">
                                            <li><a href="{{route('orderstatus.index')}}">Order Statuses </a></li>
                                            <li><a href="{{route('stockstatus.index')}}">Stock Statuses </a></li>
                                            <li><a href="{{route('lengthclass.index')}}">LengthClasses</a></li>
                                            <li><a href="{{route('weightclass.index')}}">WeightClasses</a></li>
                                            <li><a>Returns <span class="fa fa-chevron-down"></span> </a>
                                                <ul class="nav child_menu">
                                                    <li><a href="{{route('returnstatus.index')}}">Return Statuses</a>
                                                    <li><a href="{{route('returnaction.index')}}">Returns Actions</a></li>
                                                    <li><a href="{{route('returnreason.index')}}">Returns Reasons</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li> --}}
                                   {{--  <li><a>Users <span class="fa fa-chevron-down"></span> </a>
                                        <ul class="nav child_menu">
                                            <li><a href="{{route('user.index')}}">Users </a></li>
                                            <li><a href="{{route('role.index')}}">User Roles </a></li>
                                        </ul>
                                    </li> --}}
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /sidebar menu -->
                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                    <a data-toggle="tooltip" data-placement="top" title="Settings">
                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Lock">
                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                    </a>
                    <a href="{{route('logout')}}" data-toggle="tooltip" data-placement="top" title="Logout">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    </a>
                </div>
                <!-- /menu footer buttons -->
            </div>
        </div>

resources/views/admin/includes/buttons.blade.php
<div class="x_title">
    <h2><?php echo $title; ?> <small> List</small></h2>
    <div class="pull-right">
	    @if(($name=='category'))
	    	<a href="{{route('admin.'.$name.'.importexport')}}" class="btn btn-info btn-md">Import/Export
	    	</a>
	    @endif
	    <a href="{{route('admin.'.$name.'.create')}}" class="btn btn-info btn-md">
	        <span class="glyphicon glyphicon-plus"></span> Add
	    </a>
	    <a href="#" class="btn btn-danger btn-md deleteData">
	        <span class="glyphicon glyphicon-trash" ></span> Delete
	    </a>
    </div>
    <div class="clearfix"></div>
</div>

resources/views/admin/includes/header.blade.php
 <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

                  <ul class="nav navbar-nav navbar-right">
                    <li class="">
                      <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                      <!-- <img src="{{ asset('uploads/retailers/logos/image.png') }}" /> -->
                       {{--  <img src="{{ asset(Sentinel::getUser()->image)}}" alt="">{{Sentinel::getUser()->first_name}} {{Sentinel::getUser()->last_name}} --}}
                        <span class=" fa fa-angle-down"></span>
                      </a>
                      <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{{ route('changepassword') }}"> Change Password</a></li>
                        <li><a href="{{route('logout')}}"   onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                      </ul>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          {{ csrf_field() }}
                      </form>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>

 <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">

resources/views/admin/includes/session.blade.php
@if (Session::has('notifier.notice'))
    <script>
        new PNotify({!! Session::get('notifier.notice') !!});
    </script>
@endif
@if(Session::has('message'))
    <div class="alert {{ Session::get('alert-class', 'alert-info') }} fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <p>{{ Session::get('message') }}</p>
    </div>
    {{ Session::forget('message') }}
@endif

resources/views/admin/includes/sidebar.blade.php
<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar naadmin.dashboard.indexv_title" style="border: 0;">
                    {{-- @if($setting['config_logo']!='')
                        <a href="{{route('dashboard.index')}}" class="site_title"><img  src="{{ asset($setting['config_logo']) }}" alt="" style=""></a>
                    @else
                        <a href="{{route('dashboard.index')}}" class="site_title"><img  src="{{asset('')}}assets/home/images/suvalaav-logo.svg" alt="" style=""></a>
                    @endif --}}


                </div>
                <div class="clearfix"></div>
                <!-- menu profile quick info -->
                <div class="profile">
                    {{-- @if(auth()->user()->image!=='')
                        <div class="profile_pic">
                            <img src="{{ asset(Sentinel::getUser()->image)}}" alt="{{ Sentinel::getUser()->image }}" class="img-circle profile_img">
                        </div>
                    @else
                        <div class="profile_pic">
                            <img  src="{{asset('')}}assets/admin/images/defaultimage.png" alt="" class="img-circle profile_img">
                        </div>
                    @endif
                    
                    <div class="profile_info">
                        <span>Welcome,</span>
                        <h2>{{Sentinel::getUser()->first_name}} {{Sentinel::getUser()->last_name}}</h2>
                    </div> --}}
                </div>
                <!-- /menu profile quick info -->
                <br/>
                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <ul class="nav side-menu">
                        </ul>

                        <ul class="nav side-menu">
                            <li><a href="{{route('dashboard.index')}}"><i class="fa fa-dashboard fw"></i> Dashboard </a>
                            </li>
                        </ul>
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-tags fw"></i> Catalog <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{{route('category.index')}}">Categories</a></li>
                                    <li><a href="{{route('product.index')}}">Products</a></li>
                                    <li><a href="{{route('manufacturer.index')}}">Manufacturers</a></li>
                                    {{-- <li><a href="{{route('review.index')}}">Reviews</a></li> --}}
                                    {{-- <li><a href="{{route('information.index')}}">Information</a></li> --}}
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-shopping-cart fw"></i> Store <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{{route('store.index')}}">Stores</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-television fw"></i> Design <span
                                            class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{{route('banner.index')}}">Banners</a></li>
                                </ul>
                            </li>
                        </ul>
                        
                        
                        
                       
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-cog fw"></i> System <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="{{route('setting.index')}}">Site Settings </a></li>
                                </ul>
                            </li>
                        </ul>
                        
                        
                    </div>
                </div>
                <!-- /sidebar menu -->
                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                    <a data-toggle="tooltip" data-placement="top" title="Settings">
                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Lock">
                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                    </a>
                    <a href="{{route('logout')}}" data-toggle="tooltip" data-placement="top" title="Logout">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    </a>
                </div>
                <!-- /menu footer buttons -->
            </div>
        </div>